// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF3md0X0asjuP5NKH3EFypcqxFFcVVESU',
    appId: '1:1064007111573:web:7f894c5cb4a34193239c9c',
    messagingSenderId: '1064007111573',
    projectId: 'fyp-i-talea-e85df',
    authDomain: 'fyp-i-talea-e85df.firebaseapp.com',
    storageBucket: 'fyp-i-talea-e85df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCus4KK7TlFzH7j3kErbRW5W7ZgRNGNkv4',
    appId: '1:1064007111573:android:bcf280a7b41a5d6f239c9c',
    messagingSenderId: '1064007111573',
    projectId: 'fyp-i-talea-e85df',
    storageBucket: 'fyp-i-talea-e85df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZkAGIurdfL11FXvM8Carb-TGneVpAK7Q',
    appId: '1:1064007111573:ios:5e3c015003bd9d29239c9c',
    messagingSenderId: '1064007111573',
    projectId: 'fyp-i-talea-e85df',
    storageBucket: 'fyp-i-talea-e85df.appspot.com',
    iosBundleId: 'com.example.finalYearProjectItalea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZkAGIurdfL11FXvM8Carb-TGneVpAK7Q',
    appId: '1:1064007111573:ios:af122b2ef7e20a0d239c9c',
    messagingSenderId: '1064007111573',
    projectId: 'fyp-i-talea-e85df',
    storageBucket: 'fyp-i-talea-e85df.appspot.com',
    iosBundleId: 'com.example.finalYearProjectItalea.RunnerTests',
  );
}
